name: owasp scan
on: [workflow_dispatch]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    services:
      syncthing:
        image: syncthing/syncthing
    steps:        
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        continue-on-error: true
        with:
          target: 'http://127.0.0.1:8384/'
      - name: Archive zap results
        uses: actions/upload-artifact@v3
        with:
          name: zap results
          path: report*
